runtime: custom
env: flex
service: qa-integration-ms

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.75
  target_concurrent_requests: 100

resources:
  cpu: 0.5
  memory_gb: 1
  disk_size_gb: 25

env_variables:
  NODE_ENV: "staging"
